#include "auton/autons/near_side_points.h"
#include "auton/autons/near_side_winpoint.h"
#include "auton/autons/just_go_forward.h"
#include "auton/autons/far_side_winpoint.h"
#include "auton/autons/go_backwards_auton.h"
#include "auton/autons/skills_auton.h"